name: Deployment

on:
  push:
    branches: [dev] # only push events on source branch trigger deployment

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    name: A job to deploy blog.
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Cache Node Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            node -v
            npm i -g hexo-deployer-git
            npm i -g hexo-cli
            npm i -g hexo
            npm i

      - name: Configuration environment
        env:
          GIT_USER : LbhFront-end
          GIT_EMAIL : 544289495@qq.com
          HEXO_DEPLOY_PRI : ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
            sudo timedatectl set-timezone "Asia/Shanghai"
            mkdir -p ~/.ssh/
            echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts            
            git config --global user.name $GIT_USER
            git config --global user.email $GIT_EMAIL

      - name: Deploy to Github Pages
        run: |
            npx hexo deploy --generate
